// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6Hu7EsxWM_CMtln3KEXgeYn-JUgguY0',
    appId: '1:29293432271:web:61ebbb88b3ea523c7396ba',
    messagingSenderId: '29293432271',
    projectId: 'parkkaro-9e08e',
    authDomain: 'parkkaro-9e08e.firebaseapp.com',
    storageBucket: 'parkkaro-9e08e.appspot.com',
    measurementId: 'G-ZGNFD6CSZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8MRccONAK759y-0WoVJMCHsMdsqNKR0',
    appId: '1:29293432271:android:616371bec9beebdf7396ba',
    messagingSenderId: '29293432271',
    projectId: 'parkkaro-9e08e',
    storageBucket: 'parkkaro-9e08e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmabISS5rnDnkJ2idhNUa30Qacr0Bze9g',
    appId: '1:29293432271:ios:2f7383bbf411883e7396ba',
    messagingSenderId: '29293432271',
    projectId: 'parkkaro-9e08e',
    storageBucket: 'parkkaro-9e08e.appspot.com',
    iosBundleId: 'com.example.parkeaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmabISS5rnDnkJ2idhNUa30Qacr0Bze9g',
    appId: '1:29293432271:ios:d9eff189f74c57cb7396ba',
    messagingSenderId: '29293432271',
    projectId: 'parkkaro-9e08e',
    storageBucket: 'parkkaro-9e08e.appspot.com',
    iosBundleId: 'com.example.parkeaseapp.RunnerTests',
  );
}
